name: code-guard
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          # checkout the PR head ref so the workflow lints the PR content
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: |
          npm ci

      - name: Run linter (non-blocking for CTF)
        run: |
          npm run lint || true

      - name: Run tests (non-blocking)
        run: |
          npm test || true

      - name: List repo files (for debug)
        run: |
          echo "Files in repo:"
          ls -la
